# syntax=docker/dockerfile:1

# Etapa de build
FROM node:20-alpine AS builder
WORKDIR /app

# Copiar dependencias y variables opcionales
ARG VITE_API_URL=http://localhost:8080
ENV VITE_API_URL=${VITE_API_URL}

# En producción (GitHub Actions) se puede ejecutar:
# docker build -t front-prod --build-arg VITE_API_URL=https://tp8-back-prod.azurewebsites.net .

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --omit=dev

# Copiar el resto del código y construir la app
COPY . .
RUN npm run build || npm run build:prod

# Etapa de runtime (Nginx)
FROM nginx:1.27-alpine
WORKDIR /usr/share/nginx/html
COPY --from=builder /app/build/ ./
COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 80

# Comando de inicio (inyecta VITE_API_URL en env-config y arranca Nginx)
ENTRYPOINT ["/entrypoint.sh"]
